---
title: "EDS240: Self Reflection 1"
author: 'Sofia Ingersoll'
date: '2024-01-13'
---

# Self Reflection 1

### Questions about school and life:

1.  Where are you coming from (e.g. “I recently finished my undergraduate degree”, “I’ve been working in industry X for Y years”) (1-2 sentences)

I finished my B.S. in Chemistry at UCSD last June and jumped into this program two months later without any prior coding experience.

2.  What do you hope to get out of this class? (3-4 sentences)

I’m really hoping to be able to improve my previous assignments and vamp up my portfolio with our new data viz tools. I’m also hoping to gain more knowledge in html, css, sass to improve my web design skills as well for presenting deliverables. I want to create unique, effective, and aesthetically pleasing data visualizations. Also any data wrangling practice you can provide would be significantly appreciated, I don’t have very much experience with this or finding data sets.

3.  If you have a particular career goal in mind, how does this course apply to your future career, if at all? (1-3 sentences)

This class is really going to influence one of my capstone deliverables, a climate dashboard. I know I want to create sci-coms bridges for scientists, policy makers, & the public and there’s no greater way to communicate than through visualizations.

4.  What do you wish your instructors knew about you, but don’t? (2-4 sentences)

I am a DSP student and on occasion I experience disability flares. During a flare, I’m not able to perform at my usual/best and it takes a little time to get myself back up to speed. I have a good support+care system though! :-) If I experience a flare this quarter, I will reach out to keep you in the loop.

### Questions about the way you like to learn:

1.  What kinds of assignments, skills, or behaviors have you felt most comfortable with / enjoy from past classes? Why do you enjoy them? (4-5 sentences)

When learning new things, I like a code-along type learning session to first get comfortable with things. After getting some guided practice, I gain the confidence to work on new questions that apply our new skills. I really like working independently in a workshop-like environment. However, I really like how you're randomly grouping us to tackle new challenges, it's a fun way to work with new people.

2.  How confident do you feel in your data visualization skills? Why? (3-4 sentences)

On a 5 scale, I would rate my confidence a 1.5 in data visualization skills. I know very little ggplot2 specializations and can only make really basic visualizations. I feel limited by my current knowledge because I’m new to the game, but that’s gonna change. :-)

3.  How confident do you feel in your coding skills (primarily R, but feel free to elaborate on any of the languages you’ve used)? Why? (3-4 sentences)

So this is my first experience coding, but this program has given me some great tools. I am confident that I can pick up new skills quickly. With repetition and different applications of these tricks, I feel very optimistic about my ability to learn more R.

4.  What have you struggled with in the past in other graduate-level courses? Why? (3-4 sentences)

Weirdly enough, I have a hard time interpreting questions sometimes. I found that sometimes my answers were only for part of a question. This was because I didn’t realize there were deeper components required to successfully answer.

5.  Of the courses you’re taking this quarter, which do you expect to be the most challenging? Most demanding? (1-2 sentences)

The capstone project will take the most time and be the most time consuming. Following that would be 232.

6.  What responsibilities do you have outside of school, and how do you want to balance them? (3-4 sentences)

Co-chair, DAC, BSLC, part-time research assistant at The 2035 Initiative, full time cat mom of two. I’m asking the MESM student leaders to limit the length and number of our meetings for the rest of the year and focus our time solely on essential topics. In terms of balancing my workload, my Google Calendar has a pretty beefy working session schedule for the quarter, that I’m hoping I’ll be able to stick to.

7.  Which learning goals from the syllabus are you most excited about? (3-4 sentences)

There's a lot of good of goals I'm excited about, but the biggest one is writing code from scratch and adapting new code written by others. I'm looking forward applying a DEI lens to the process of designing data visualizations. Finally, I'm most excited about preparing tidy data to build quality data visualizations.

8.  Most importantly, how do you plan on accomplishing your learning goals for this course? Note: be specific here! Instead of writing, “I will complete homework assignments” or “I will study”, you can make these more specific strategies: “I will create a schedule to map out assignments“ (elaborate on this), “I will use the homework assignments as opportunities to practice X,” I will communicate with classmates to ask for help after trying X,” “I will participate in online learning communities, such as TidyTuesday…” etc. (5-8 sentences)

Using a blocking schedule, I will be able to focus my time on specific tasks and developing new skills. This will also allow me a better ability to balance my extra-curriculars and work. Keeping an agenda book and a notebook to write down assignments, networking events, and project deadlines. To strengthen my understanding, I will be utilizing all of the resources provided in this course, as well as, the materials from our insightful career workshops. I will bolster my portfolio through the implementation of the skills practiced in this course. Additionally, the writing portion of my projects are to all contain DEI considerations.

### Fun questions:

1.  What activity(ies) (outside of school / work) brings you the most joy? How do you plan to incorporate that activity into your schedule this quarter (if at all)? If you are unable to do so, is there something else you can plan to do that will bring you similar joy? (3-5 sentences)

Zumba gives me so much life and excitement for the week, I plan on keeping that in my Saturday morning routine. I really love doing yoga and I’m hoping to go Thursday nights and Sunday mornings. Sol Seek does some nice classes at La Mesa park and Leadbetter beach. I’m also really hoping to explore the area more and take a trip out to the Channel Islands, maybe do some camping, but now I’m kind of daydreaming.

2.  What is a piece of media you enjoyed recently? (e.g. music, book, movie, tweet, meme) (2-4 sentences)

I recently fell into Anthony Bourdain’s Parts Unknown series on HBOMax. It’s been an intriguing tv palette cleanser after watching Gilmore Girls nonstop for the last 3 weeks.
