---
title: "Discussion 3"
author: "Sofia Ingersoll"
date: "2024-01-24"
---
```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(tidyverse)

#..........................import data...........................
tuesdata <- tidytuesdayR::tt_load('2021-07-20')
drought <- tuesdata$drought

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                            wrangle drought data                          ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean <- drought |>

  # select cols of interest & update names as needed ----
  select(date = valid_start, state_abb, drought_lvl, area_pct) |> 

  # add year, month & day cols using {lubridate} fxns ----
  mutate(year = year(date),
         month = month(date, label = TRUE, abbr = TRUE),
         day = day(date)) |>

  # add drought level conditions names ----
  mutate(drought_lvl_long = factor(drought_lvl,
                            levels = c("D4", "D3", "D2", "D1","D0", "None"),
                            labels = c("(D4) Exceptional",
                                       "(D3) Extreme",
                                       "(D2) Severe", 
                                       "(D1) Moderate", 
                                       "(D0) Abnormally Dry", 
                                       "No Drought"))) |>
  
  # reorder cols ----
  select(date, year, month, day, state_abb, drought_lvl, drought_lvl_long, area_pct)

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##       create stacked area plot of CA drought conditions through time     ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean |> 
  
  # remove drought_lvl "None" & filter for just CA ----
  filter(drought_lvl != "None",
         state_abb == "CA") |> 
  
  # create ggplot ----
  ggplot(mapping = aes(x = date, y = area_pct, fill = drought_lvl_long)) +
  
  # reverse order of groups so level D4 is closest to x-axis ----
  geom_area(position = position_stack(reverse = TRUE)) +
  
  # update colors to match US Drought Monitor (colors selected using ColorPick Eyedropper from original USDM data viz) ----
  scale_fill_manual(values = c("#853904", "#FF0000", "#FFC100", "#FFD965", "#FFFF00")) +
  
  # set x-axis breaks & remove padding between data and x-axis ----
  scale_x_date(breaks = scales::breaks_pretty(n = 10),
               expand = c(0, 0)) +

  # set y-axis breaks & convert values to percentages & & remove padding between data and y-axis----
  scale_y_continuous(breaks = seq(0, 100, by = 10),
                     labels = scales::label_percent(scale = 1),
                     expand = c(0, 0)) +
  
  # add title ----
  labs(title = "Drought area in California") 

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##            BONUS: using {geofacet} to plot data for all states           ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#......remove HI & AK (no data) and also DC from preset grid.....
mygrid <- geofacet::us_state_grid1 |>
  filter(!code %in% c("DC", "HI", "AK"))

#..............................plot..............................

# NOTE: this takes a minute to render!

drought_clean |> 
  filter(drought_lvl != "None") |> 
  ggplot(aes(x = date, y = area_pct, fill = drought_lvl_long)) +
  geom_area(position = position_stack(reverse = TRUE)) +
  geofacet::facet_geo(~state_abb, grid = mygrid) +
  scale_fill_manual(values = c("#853904", "#FF0000", "#FFC100", "#FFD965", "#FFFF00"))
```

```{r}
# Rdigeline Plot
# ridgeline plot (x = month, y = drought_lvl, fill = state_abb)
# orignial plot
drought_clean %>% 
  mutate(month_name = factor(month_name, levels = month.name))  %>%            # arrange variables in the same order indexed in variable month.name order
  ggplot() +
  geom_histogram(aes(x = state_abb,
                 fill = month_name),
                 position = "identity",
                 alpha = 0.5)

ggplot(mko_clean, aes(x = Temp_bot,
                      y = month_name,
                      fill = after_stat(x))) +                        # do the stat function transformation and then apply color mapping
  ggridges::geom_density_ridges_gradient(rel_min_height = 0.01,       # the smaller you get, the more stretched it becomes 
                                         scale = 3) +                 # this creates overlap of densities  
  scale_y_discrete(limits = month.name) +
  scale_fill_gradientn(colors = c('hotpink','lightpink', 'lavender', 'plum', 'purple'))

# within geom_density_ridges
#jittered_points = TRUE,
                                        # alpha = 0.5,
                                       #  point_size = 0.5,

```

```{r}
ggplot(drought, aes(x = state_abb, y = drought_lvl,
                      # color by x-variable and will be dictated by the gradient later set
                      fill = after_stat(x))) +
  # call ridges plot, and set how long tails of data will show
  ggridges::geom_density_ridges_gradient(rel_min_height = 0.01,
                                         # sets overlap of ridges, higher number = more overlap
                                         scale = 3) +
  coord_flip()
```

