
---
title: "EDS 240 Lecture 4 Notebook"
author: "Sofia Ingersoll"
date: 2024-01-29
---
```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(metajam)              # use this to scrape dataone data
library(tidyverse)

#...................download data from DataOne...................
# comment out after successfully downloading
#download_d1_data("https://cn.dataone.org/cn/v2/resolve/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-hbr%2F208%2F9%2F3b3cf7ea447cb875d7c7d68ebdfd24c7",
#path = here::here("wk4")) 

#  ~ NOTE: I recommend renaming the downloaded folder to 'data/' so that it's ignored by .gitignore! ~

#....................read in downloaded files....................
stream_chem_all <- read_d1_files(here::here("wk4", "data"))

#........................get the data file.......................
stream_chem_data <- stream_chem_all$data

```

## Basic Scatterplot

```{r}

p1 <- stream_chem_data %>% 
  filter(waterYr == 2021) %>% 
  ggplot(
    aes(
      x = DOC,
      y = pH,
    )
  ) +
  geom_point(alpha = 0.5,
             col = 'violet',
             size = 2) +
  geom_rug(col = 'plum')

```

## ggextra

```{r}
ggExtra::ggMarginal(p1,
                    type = 'density',
                    col = 'plum')
```

```{r}
p2 <- stream_chem_data |> 
  filter(waterYr == 2021) |> 
  ggplot(
    aes(
      x = DOC,
      y = pH,
      color = site
    )
  ) + 
  geom_point(alpha = 0.5) +
  theme(legend.position = "bottom")

ggExtra::ggMarginal(p2, type = "density", groupFill = TRUE, groupColour = TRUE)
```             


```{r}
stream_chem_data %>% 
  filter(waterYr == 2021) %>% 
  filter(site == "W8") %>% 
  ggplot(
    aes(
      x = DOC,
      y = pH
    )
  ) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = 'lm', se = FALSE)   # error ribbons can falsely lead the audience to believe this is a true estimate of trends in data. this is not the best fit line for nonlinear data
```

## 3 variables in a scatterplot

```{r}
 stream_chem_data |> 
  filter(waterYr == 2021) |> 
  ggplot(
    aes(
      x = DOC,
      y = pH,
      color = site,
      size = Al_ICP
    )
  ) + 
  geom_point(alpha = 0.5) +
  scale_size(range = c(1,10))        # scales bubles by area this is most appropriate and is less deciving to the eye
```
```{r}
ggplot(stream_chem_data,
       aes(
         x = SO4,
         y = pH,
         color = site
       )) +
  geom_point(alpha = 0.5,
             size = 0.5) +
  geom_rug()



# binned 2d plot of heatmaps ----
ggplot(stream_chem_data,
       aes(
         x = SO4,
         y = pH
       )) +
  geom_bin2d() +
  scale_fill_colorhex_c()


# hex map
ggplot(stream_chem_data,
       aes(
         x = SO4,
         y = pH
       )) +
  geom_hex() +
  scale_fill_colorhex_c() +
  guides(fill = guide_colorbar(title = 'Count',
                               barwidth = 1,
                               barheight = 15))

```

